steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Deploying DICOM processing Cloud Function..."

        gcloud functions deploy process_dicom_file \
          --runtime python310 \
          --entry-point process_dicom_file \
          --trigger-resource tp_dicom_files \
          --trigger-event google.storage.object.finalize \
          --source . \
          --region us-central1 \
          --memory 512MB \
          --timeout 300s \
          --quiet

options:
  logging: CLOUD_LOGGING_ONLY